framework:
    cache:
        pools:
            app.cache.redis:
                adapter: cache.adapter.redis
                default_lifetime: 3600
        default_redis_provider: '%env(REDIS_URL)%'
    lock:
        resources:
            redis:
                connection: '%env(REDIS_URL)%'
